### ISSUE TITLE
nimsl.nim(75, 60) Error: type mismatch: got (array[0..1, float32]) but expected 'vec2 = vecBase[2, system.float32]'

### ISSUE THREAD

**Issue by retsyo** [yglukhov/nimsl#1]
I am a new user, and I can't judge whether the bug is lie in nim or nimsl

I am using MSYS2+MingW64 on Win7 64 bits. And I built the latest nim from github's source
I have deleted all the pkg, and  `./nimble install nimx`  takes a long time to run. However,  `./nim c -r --noMain --threads:on /e/prg/nim/my_code/test_nimx.nim`  says
```nim
C:\Users\USR\.nimble\pkgs\nimsl-0.2\nimsl\nimsl.nim(75, 60) Error: type mismatch: got (array[0..1, float32]) but expected 'vec2 = vecBase[2, system.float32]'
```

the `test_nimx.nim`  is
```nim
# File: main.nim
import nimx.window
import nimx.text_field
import nimx.system_logger # Required because of Nim bug (#4433)

proc startApp() =
    # First create a window. Window is the root of view hierarchy.
    var wnd = newWindow(newRect(40, 40, 800, 600))

    # Create a static text field and add it to view hierarchy
    let label = newLabel(newRect(20, 20, 150, 20))
    label.text = "Hello, world!"
    wnd.addSubview(label)

# Run the app
runApplication:
    startApp()
'''

**Comment by yglukhov** [comment]
That's a bug in Nim. Will be fixed when https://github.com/nim-lang/Nim/pull/5677 is merged. Until then you can use Nim revision 0ccbc8234.

**Comment by yglukhov** [comment]
Should work with latest nim devel now. Please reopen if it doesn't.
